### ISSUE TITLE
Throw error when SecurityTokenService is unavailable.

### ISSUE THREAD

**Issue by baardl** [Cantara/Whydah-Java-SDK#15]
This is hidden in a error 500 today.
Eg. used in ApplicationSession

**Comment by baardl** [comment]
Example of output when STS is unavailable:
Caused by: java.lang.IllegalArgumentException: Missing parameters for 
	tokenServiceUri [http://localhost:9998/tokenservice], 
	myAppTokenId [null], 
	myAppTokenXml[null] or 
	userCredential[UserNameAndPasswordCredential{userName='xxxxxx}]
	at net.whydah.sso.commands.userauth.CommandLogonUserByUserCredential.<init>(CommandLogonUserByUserCredential.java:45) ~[Whydah-Java-SDK-2.0.33-SNAPSHOT.jar:na]
	at net.whydah.sso.commands.userauth.CommandLogonUserByUserCredential.<init>(CommandLogonUserByUserCredential.java:54) ~[Whydah-Java-SDK-2.0.33-SNAPSHOT.jar:na]
	at net.whydah.sso.WhydahUtil.logOnUser(WhydahUtil.java:99) ~[Whydah-Java-SDK-2.0.33-SNAPSHOT.jar:na]

**Comment by totto** [comment]
The Application Session is meant to survive short period of network problems against STS and other services

**Comment by totto** [comment]
Most commands will tell you this now...  please create an issue for commands which does not communicate this correctly
